### ISSUE TITLE
[BUG] Space Exploration's High Temperature Turbine Generator does not produce energy

### ISSUE THREAD

**Issue by Voker57** [Omnimods/Omnimods#427]
**Describe the bug**
With SE+Omnipermute the HTTG shows up as 0 W in power distribution. SE author says that is a Omnipermute bug

**To Reproduce**
1. Set up HTTG
2. Watch it consume/produce items normally but not power

**Expected behavior**
1. HTTG produces 1 GW

**Screenshots**
a video: https://cdn.discordapp.com/attachments/1164303297323212820/1164304982879780955/2023-10-18_23-51-45.mkv

**Additional context**

**Additional Info**
- Factorio Version: 1.1.91
- Minimal required mods to reproduce: SE + Omnipermute
- Savegame:

**Comment by Cereal-Sam** [comment]
Thanks for the detailed info.
I thought about going the route you explained about excluding all recipes that are only accessible in furnaces first.
Certain mods (omnimatter as well for example) add assembling machine type entities that are capable of crafting furnace only crafting categories.
This would mean, that this would be an issue again when such mods are present.
I added the internal furnace recipe to the exclusion list for now.
The issue will be fixed with the next mod portal release.
